### ISSUE TITLE
Standardize Form Control Look and Feel on Mobile Safari

### ISSUE THREAD

**Issue by jhabdas** [egoist/hack#63]
Using hack without a css reset of any kind we can see some elements are unstyled to achieve the expected look-and-feel:

https://github.com/egoist/hack/blob/5843d8991923b5995c3be2419e381fa80664c990/src/css/components.css#L139-L141

Let's extend this also to input controls for mobile safari. Here's a primer for making it happen: https://signalvnoise.com/posts/2609-customizing-web-forms-with-css3-and-webkit

**Comment by jhabdas** [comment]
Similarly we should test for and disable auto-zoom on input controls: https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone

**Comment by jhabdas** [comment]
If we want to look at disable zooming on controls for Safari Mobile extend this:

```css
input.form-control,
textarea.form-control {
  font-size: initial;
}
```

**Comment by jhabdas** [comment]
How @guitmz addressed this:

https://github.com/guitmz/after-dark-green/blob/1e953866a04b604d1e277038217e38af3744cd6d/layouts/partials/head/critical-theme.css#L73-L79

**Comment by jhabdas** [comment]
How @guitmz addressed this in

```css
input.form-control {
  border-radius: 0;
  background-color: transparent;
  -webkit-appearance: none;
  -moz-appearance: none;
  -ms-appearance: none;
}
```

**Comment by jhabdas** [comment]
How @guitmz addressed this:

```css
input.form-control {
  border-radius: 0;
  background-color: transparent;
  -webkit-appearance: none;
  -moz-appearance: none;
  -ms-appearance: none;
}
```
